version: '3.8'

services:
  withyou-app:
    # image: prunsoli/withyou-test:0.0.7
    image : prunsoli/withyou-test:0.0.4
    container_name: withyou-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=test
    depends_on:
      - redis
    networks:
      - withyou-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: withyou-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - withyou-network
    restart: unless-stopped

networks:
  withyou-network:
    driver: bridge

volumes:
  redis-data: