spring:
  datasource:
    url: ENC(QeReaxcbOPs1Vh1OWz/DEsWJjixf/A5uD4qlPpYV45RkoGrvbQ8zf/Ige9VAtNrfzdhtPxGqtYz+O24aRTNe5E/PbIIEKmOYZEL2evom+/GN03b0IxnmGEZwW9kNfuULzacp/zww9Vwblk8uUcTnpyKMlAURf+1jSYa0z+E0WMsKfvwpHznE0A==)
    username: ENC(Lpbrj2H0Ev8wFSsWAeD7zw==)
    password: ENC(yFf5npxaSWLr8hXwMR6ZbvASn0RSN8mx)
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

cloud:
  aws:
    s3:
      bucket: ENC(PL3eeYTb8i9ifHB0csm1HrOMxGJUy31Q)
    stack.auto: false
    region.static: ENC(AO7hsXhDxXaKlvb661lADnll3Wex9cz7)
    credentials:
      accessKey: ENC(LYSekTBrws9Ru1VLVtdbadnRb3n8IYf6pJqpTv3IpOo=)
      secretKey: ENC(vYct9ku08uS4w0OfDsdAhY8kZLrPoAMvh2AdzEY6OMFioByGHXcFafAUEeU7ZuFpuidpJn3cNNA=)
